### ISSUE TITLE
dependency build errors on Windows 10

### ISSUE THREAD

**Issue by elvogel** [greglobinski/gatsby-starter-hero-blog#14]
When trying to set up this site I get the following error in the yarn install process:

```text
[4/4] Building fresh packages...
[1/7] ⠁ sharp
[-/7] ⠁ waiting...
[-/7] ⠁ waiting...
[4/7] ⠁ deasync
error c:\Repos\websites\bo3\node_modules\styled-jsx-plugin-postcss\node_modules\deasync, c:\Repos\websites\bo3\node_modules\styled-jsx-plugin-stylelint\node_modules\deasync: Command failed.
Exit code: 1
Command: node ./build.js
Arguments:
Directory: c:\Repos\websites\bo3\node_modules\styled-jsx-plugin-stylelint\node_modules\deasync
Output:
c:\Repos\websites\bo3\node_modules\styled-jsx-plugin-stylelint\node_modules\deasync>if not defined npm_config_node_gyp (node "C:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.6.0 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'c:\\Repos\\websites\\bo3\\node_modules\\styled-jsx-plugin-stylelint\\node_modules\\deasync\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\endpo\\.node-gyp\\10.6.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\endpo\\.node-gyp\\10.6.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\endpo\\.node-gyp\\10.6.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=c:\\Repos\\websites\\bo3\\node_modules\\styled-jsx-plugin-stylelint\\node_modules\\deasync',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'c:\\Repos\\websites\\bo3\\node_modules\\styled-jsx-plugin-stylelint\\node_modules\\deasync\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [c:\Repos\websites\bo3\node_modules\styled-jsx-plugin-stylelint\node_modules\deasync\build\binding.sln]gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Repos\websites\bo3\node_modules\styled-jsx-plugin-stylelint\node_modules\deasync
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.6.2
```

**Comment by greglobinski** [comment]
Take a look at this https://www.gatsbyjs.org/docs/gatsby-on-windows/

**Comment by elvogel** [comment]
That was exactly what I needed. Thank you!
