### ISSUE TITLE
Issue with set up

### ISSUE THREAD

**Issue by GregBorrelly** [greglobinski/gatsby-starter-hero-blog#62]
Can't install the theme locally, it fails with `Command failed: yarnpkg`

**Versions** 
Node v11.2.0
NPM 6.4.1
Gatsby 2.4.5
Yarn 1.12.3

**Console output** 

`➜  development gatsby new myBlog  https://github.com/greglobinski/gatsby-starter-hero-blog.git

info Creating new site from git: https://github.com/greglobinski/gatsby-starter-hero-blog.git
Cloning into 'myBlog'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 748 (delta 0), reused 1 (delta 0), pack-reused 743
Receiving objects: 100% (748/748), 9.29 MiB | 22.86 MiB/s, done.
Resolving deltas: 100% (360/360), done.
success Created starter directory layout
info Installing packages...
yarn install v1.12.3
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.3: The platform "linux" is incompatible with this module.
info "fsevents@1.2.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.2: The platform "linux" is incompatible with this module.
info "fsevents@1.2.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
warning multiyargs@1.0.0: The engine "yargs" appears to be invalid.
[3/4] Linking dependencies...
warning "antd > rc-editor-mention@1.1.6" has unmet peer dependency "immutable@^3.7.4".
warning " > eslint-plugin-graphql@2.1.1" has unmet peer dependency "graphql@^0.12.0 || ^0.13.0".
warning " > url-loader@1.1.1" has unmet peer dependency "webpack@^4.0.0".
warning "gatsby-plugin-netlify > webpack-assets-manifest@3.0.2" has unmet peer dependency "webpack@>=4.0.0".
warning " > gatsby-plugin-styled-jsx@3.0.1" has incorrect peer dependency "styled-jsx@^3.0.2".
warning " > react-addons-perf@15.4.2" has incorrect peer dependency "react-dom@^15.4.2".
warning "react-instantsearch > react-instantsearch-native@5.2.2" has unmet peer dependency "react-native@>= 0.32.0".
warning "react-instantsearch > react-instantsearch-core > algoliasearch-helper@2.26.1" has unmet peer dependency "algoliasearch@>= 3.1 < 4".
warning " > postcss-cssnext@3.1.0" has unmet peer dependency "caniuse-lite@^1.0.30000697".
[4/4] Building fresh packages...
[1/5] ⠄ sharp
[2/5] ⠄ pngquant-bin
[3/5] ⠄ cwebp-bin
[4/5] ⠄ deasync
error /home/greg/development/myBlog/node_modules/deasync: Command failed.
Exit code: 1
Command: node ./build.js
Arguments: 
Directory: /home/greg/development/myBlog/node_modules/deasync
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.2.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/greg/development/myBlog/node_modules/deasync/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/greg/.node-gyp/11.2.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/greg/.node-gyp/11.2.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/greg/.node-gyp/11.2.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/greg/development/myBlog/node_modules/deasync',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:161:21)
gyp ERR! System Linux 4.15.0-38-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/greg/development/myBlog/node_modules/deasync
gyp ERR! node -v v11.2.0

error Command failed: yarnpkg

  Error: Command failed: yarnpkg
  
  - index.js:236 Promise.all.then.arr
    [lib]/[gatsby-cli]/[execa]/index.js:236:11
  
  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18
  
  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10
  
  - promise.js:694 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18
  
  - promise.js:638 Promise._fulfill
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:638:18
  
  - promise_array.js:126 PromiseArray._resolve
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:126:19
  
  - promise_array.js:144 PromiseArray._promiseFulfilled
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise_array.js:144:14
  
  - promise.js:574 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:574:26
  
  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10
  
  - promise.js:694 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:694:18
  
  - async.js:138 _drainQueueStep
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:138:12
  
  - async.js:131 _drainQueue
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:131:9
  
  - async.js:147 Async._drainQueues
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:147:5
  
  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [lib]/[gatsby-cli]/[bluebird]/js/release/async.js:17:14
`

**Comment by GregBorrelly** [comment]
After doing some follow up research, the issue seems to be with installing the sharp library. Try manually building it but no luck.

**Comment by GregBorrelly** [comment]
Ok so finally got to the root of the problem. The sharp library only supports up to Node 10.0.0 

"Pre-compiled binaries for sharp are provided for use with Node versions 6, 8 and 10 on 64-bit Windows, OS X and Linux platforms."
