### ISSUE TITLE
Initial Setup failing

### ISSUE THREAD

**Issue by 1nullpointer** [greglobinski/gatsby-starter-hero-blog#66]
### Seeing below Error when I run gatsby develop

here ./.cache/develop-static-entry.js
Module build failed (from ./node_modules/gatsby/dist/utils/babel-loader.js):
Error: Could not locate the bindings file. Tried:
 → /Users/Rakesh/Desktop/Project/WebWorkspace/GatsbySpace/myblog4/node_modules/deasync/build/deasync.node
 → /Users/Rakesh/Desktop/Project/WebWorkspace/GatsbySpace/myblog4/node_modules/deasync/build/Debug/deasync.node
 → /Users/Rakesh/Desktop/Project/WebWorkspace/GatsbySpace/myblog4/node_modules/deasync/build/Release/deasync.node
 → /Users/Rakesh/Desktop/Project/WebWorkspace/GatsbySpace/myblog4/node_modules/deasync/out/Debug/deasync.node
 → /Users/Rakesh/Desktop/Project/WebWorkspace/GatsbySpace/myblog4/node_modules/deasync/Debug/deasync.node
 → /Users/Rakesh/Desktop/Project/WebWorkspace/GatsbySpace/myblog4/node_modules/deasync/out/Release/deasync.node
 → /Users/Rakesh/Desktop/Project/WebWorkspace/GatsbySpace/myblog4/node_modules/deasync/Release/deasync.node
 → /Users/Rakesh/Desktop/Project/WebWorkspace/GatsbySpace/myblog4/node_modules/deasync/build/default/deasync.node
 → /Users/Rakesh/Desktop/Project/WebWorkspace/GatsbySpace/myblog4/node_modules/deasync/compiled/10.12.0/darwin/x64/deasync.node
    at bindings (/Users/Rakesh/Desktop/Project/WebWorkspace/GatsbySpace/myblog4/node_modules/bindings/bindings.js:88:9)
    at /Users/Rakesh/Desktop/Project/WebWorkspace/GatsbySpace/myblog4/node_modules/deasync/index.js:34:32
    at Object.<anonymous> (/Users/Rakesh/Desktop/Project/WebWorkspace/GatsbySpace/myblog4/node_modules/deasync/index.js:76:2)
    at Module._compile (/Users/Rakesh/Desktop/Project/WebWorkspace/GatsbySpace/myblog4/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (/Users/Rakesh/Desktop/Project/WebWorkspace/GatsbySpace/myblog4/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/Rakesh/Desktop/Project/WebWorkspace/GatsbySpace/myblog4/node_modules/styled-jsx-plugin-postcss/index.js:1:81)
    at Module._compile (/Users/Rakesh/Desktop/Project/WebWorkspace/GatsbySpace/myblog4/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (/Users/Rakesh/Desktop/Project/WebWorkspace/GatsbySpace/myblog4/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at /Users/Rakesh/Desktop/Project/WebWorkspace/GatsbySpace/myblog4/node_modules/styled-jsx/dist/_utils.js:421:13
    at Array.map (<anonymous>)
    at combinePlugins (/Users/Rakesh/Desktop/Project/WebWorkspace/GatsbySpace/myblog4/node_modules/styled-jsx/dist/_utils.js:410:18)
    at PluginPass.enter (/Users/Rakesh/Desktop/Project/WebWorkspace/GatsbySpace/myblog4/node_modules/styled-jsx/dist/babel.js:248:55)
error There was an error compiling the html.js component for the development server.

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  WebpackError: ./.cache/develop-static-entry.js

efinition:1 Object.<anonymous>
    lib/webpack/universalModuleDefinition:1:1

**2. Also the initial clone command is giving below error** 

info This module is OPTIONAL, you can safely ignore this error
error Command failed: yarnpkg

  Error: Command failed: yarnpkg

  - index.js:236 Promise.all.then.arr
    [lib]/[gatsby-cli]/[execa]/index.js:236:11

  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [lib]/[gatsby-cli]/[bluebird]/js/release/pro

**Comment by Warchant** [comment]
Same problem

**Comment by paddymccallan** [comment]
I did this > 
-  Remove node_modules & package-lock.json
-  Then use nvm(node version manager) to switch to node version 8.16
-  npm install
-  gatsby develop
